version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LIVEKIT_URL=wss://voyageai-3t6pxcz2.livekit.cloud
      - LIVEKIT_API_KEY=APIbG43kQfcWwgN
      - LIVEKIT_API_SECRET=STno2Ssz2hfZQVGv7uBuwt02becdrVM4yfSzsmsbapgA
      - DEEPGRAM_API_KEY=462ef79f7416fd6ee414a4851c6ffa0acc2def0c
      - CARTESIA_API_KEY=sk_car_gSSLXcAQvqQQYRDgYQ67YX
      - GOOGLE_API_KEY=AIzaSyBN7QW7yE4kfQOshNMmegyAt0mZYXhvqnQ
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./backend:/app
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  frontend:
    build:
      context: ./react app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react app:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # Note: LiveKit is now using cloud service, so we don't need to run it locally
  # livekit:
  #   image: livekit/livekit-server
  #   ports:
  #     - "7880:7880"
  #     - "7881:7881"
  #     - "7882:7882/udp"
  #   environment:
  #     - LIVEKIT_KEYS=devkey: secret
  #   volumes:
  #     - ./livekit.yaml:/livekit.yaml
  #   command: --config /livekit.yaml --node-ip localhost --cpuprofile --memprofile
  #   networks:
  #     - app-network
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1.0'
  #         memory: 1G
  #       reservations:
  #         cpus: '0.5'
  #         memory: 512M

networks:
  app-network:
    driver: bridge